// GENERATED by scripts/derive-fixture.mjs — do not edit by hand; re-run the script.
// Source: production-04-remote-interaction (run 20260724T134007Z), checked in under captures/
// (see captures/README.md for provenance). Projection: allowlist only, integrity
// hashes dropped, URLs sanitized to origin + path, only fields the Phase-1 views need.

import { SnapshotV1 } from '../snapshot-v1';

export const frankensteinProductionFixture = {
  "schemaVersion": 1,
  "capture": {
    "pageUrl": "http://127.0.0.1:8088/frankenstein-meeting-room/",
    "capturedAt": "2026-07-24T13:50:22.812Z",
    "mode": "passive",
    "collectorVersion": "frankenstein-runtime-capture/1"
  },
  "channels": {
    "nativeFederationGlobals": {
      "state": "available"
    },
    "domImportMaps": {
      "state": "available"
    },
    "importShim": {
      "state": "available"
    }
  },
  "runtime": {
    "remotes": {
      "__NF-HOST__": {
        "scopeUrl": "http://127.0.0.1:8088/frankenstein-meeting-room/",
        "exposes": []
      },
      "mermaid": {
        "scopeUrl": "http://127.0.0.1:8088/frankenstein-meeting-room/mermaid/",
        "exposes": [
          {
            "moduleName": "http://127.0.0.1:8088/frankenstein-meeting-room/Bootstrap",
            "file": "Bootstrap-BBNZEAEH.js"
          }
        ]
      },
      "whiteboard": {
        "scopeUrl": "http://127.0.0.1:8088/frankenstein-meeting-room/whiteboard/",
        "exposes": [
          {
            "moduleName": "http://127.0.0.1:8088/frankenstein-meeting-room/Bootstrap",
            "file": "Bootstrap-7COJRA5I.js"
          }
        ]
      }
    },
    "scopedExternals": {},
    "sharedExternals": {
      "__GLOBAL__": {
        "@angular/common": {
          "dirty": false,
          "versions": [
            {
              "tag": "21.2.12",
              "action": "share",
              "host": true,
              "remotes": [
                {
                  "name": "__NF-HOST__",
                  "requiredVersion": "^21.2.0",
                  "strictVersion": true,
                  "file": "_angular_common.Ucn2BmyRM1.js",
                  "cached": true
                }
              ]
            }
          ]
        },
        "@angular/common/http": {
          "dirty": false,
          "versions": [
            {
              "tag": "21.2.12",
              "action": "share",
              "host": true,
              "remotes": [
                {
                  "name": "__NF-HOST__",
                  "requiredVersion": "^21.2.0",
                  "strictVersion": true,
                  "file": "_angular_common_http.XnycUwbhpt.js",
                  "cached": true
                }
              ]
            }
          ]
        },
        "@angular/core": {
          "dirty": false,
          "versions": [
            {
              "tag": "21.2.12",
              "action": "share",
              "host": true,
              "remotes": [
                {
                  "name": "__NF-HOST__",
                  "requiredVersion": "^21.2.0",
                  "strictVersion": true,
                  "file": "_angular_core.RHjtWEkOzP.js",
                  "cached": true
                }
              ]
            }
          ]
        },
        "@angular/core/event-dispatch-contract.min.js": {
          "dirty": false,
          "versions": [
            {
              "tag": "21.2.12",
              "action": "share",
              "host": true,
              "remotes": [
                {
                  "name": "__NF-HOST__",
                  "requiredVersion": "^21.2.0",
                  "strictVersion": true,
                  "file": "_angular_core_event_dispatch_contract_min_js.JotK85OfcE.js",
                  "cached": true
                }
              ]
            }
          ]
        },
        "@angular/core/primitives/di": {
          "dirty": false,
          "versions": [
            {
              "tag": "21.2.12",
              "action": "share",
              "host": true,
              "remotes": [
                {
                  "name": "__NF-HOST__",
                  "requiredVersion": "^21.2.0",
                  "strictVersion": true,
                  "file": "_angular_core_primitives_di.QUc60-Xs6C.js",
                  "cached": true
                }
              ]
            }
          ]
        },
        "@angular/core/primitives/event-dispatch": {
          "dirty": false,
          "versions": [
            {
              "tag": "21.2.12",
              "action": "share",
              "host": true,
              "remotes": [
                {
                  "name": "__NF-HOST__",
                  "requiredVersion": "^21.2.0",
                  "strictVersion": true,
                  "file": "_angular_core_primitives_event_dispatch.1A9qBws3LP.js",
                  "cached": true
                }
              ]
            }
          ]
        },
        "@angular/core/primitives/signals": {
          "dirty": false,
          "versions": [
            {
              "tag": "21.2.12",
              "action": "share",
              "host": true,
              "remotes": [
                {
                  "name": "__NF-HOST__",
                  "requiredVersion": "^21.2.0",
                  "strictVersion": true,
                  "file": "_angular_core_primitives_signals.ePwPWbaXlE.js",
                  "cached": true
                }
              ]
            }
          ]
        },
        "@angular/core/rxjs-interop": {
          "dirty": false,
          "versions": [
            {
              "tag": "21.2.12",
              "action": "share",
              "host": true,
              "remotes": [
                {
                  "name": "__NF-HOST__",
                  "requiredVersion": "^21.2.0",
                  "strictVersion": true,
                  "file": "_angular_core_rxjs_interop.YqevhcoUQy.js",
                  "cached": true
                }
              ]
            }
          ]
        },
        "@angular/platform-browser": {
          "dirty": false,
          "versions": [
            {
              "tag": "21.2.12",
              "action": "share",
              "host": true,
              "remotes": [
                {
                  "name": "__NF-HOST__",
                  "requiredVersion": "^21.2.0",
                  "strictVersion": true,
                  "file": "_angular_platform_browser.lAyP2N3Pw8.js",
                  "cached": true
                }
              ]
            }
          ]
        },
        "@excalidraw/excalidraw": {
          "dirty": false,
          "versions": [
            {
              "tag": "0.18.1",
              "action": "share",
              "host": false,
              "remotes": [
                {
                  "name": "whiteboard",
                  "requiredVersion": "~0.18.1",
                  "strictVersion": true,
                  "file": "_excalidraw_excalidraw.0MlOv2WvQj.js",
                  "cached": true
                }
              ]
            }
          ]
        },
        "mermaid": {
          "dirty": false,
          "versions": [
            {
              "tag": "11.14.0",
              "action": "share",
              "host": false,
              "remotes": [
                {
                  "name": "mermaid",
                  "requiredVersion": "^11.4.1",
                  "strictVersion": true,
                  "file": "mermaid.fMI3T940QA.js",
                  "cached": true
                }
              ]
            }
          ]
        },
        "react": {
          "dirty": false,
          "versions": [
            {
              "tag": "18.3.1",
              "action": "share",
              "host": false,
              "remotes": [
                {
                  "name": "whiteboard",
                  "requiredVersion": "^18.3.1",
                  "strictVersion": true,
                  "file": "react.QYXZqQxJ1j.js",
                  "cached": true
                }
              ]
            }
          ]
        },
        "react-dom": {
          "dirty": false,
          "versions": [
            {
              "tag": "18.3.1",
              "action": "share",
              "host": false,
              "remotes": [
                {
                  "name": "whiteboard",
                  "requiredVersion": "^18.3.1",
                  "strictVersion": true,
                  "file": "react_dom.6SKyvL_ZIW.js",
                  "cached": true
                }
              ]
            }
          ]
        },
        "react-dom/client": {
          "dirty": false,
          "versions": [
            {
              "tag": "18.3.1",
              "action": "share",
              "host": false,
              "remotes": [
                {
                  "name": "whiteboard",
                  "requiredVersion": "^18.3.1",
                  "strictVersion": true,
                  "file": "react_dom_client.lVKcx-4-HL.js",
                  "cached": true
                }
              ]
            }
          ]
        },
        "react-dom/profiling": {
          "dirty": false,
          "versions": [
            {
              "tag": "18.3.1",
              "action": "share",
              "host": false,
              "remotes": [
                {
                  "name": "whiteboard",
                  "requiredVersion": "^18.3.1",
                  "strictVersion": true,
                  "file": "react_dom_profiling.wPFH8wjIJf.js",
                  "cached": true
                }
              ]
            }
          ]
        },
        "react/jsx-dev-runtime": {
          "dirty": false,
          "versions": [
            {
              "tag": "18.3.1",
              "action": "share",
              "host": false,
              "remotes": [
                {
                  "name": "whiteboard",
                  "requiredVersion": "^18.3.1",
                  "strictVersion": true,
                  "file": "react_jsx_dev_runtime.UsMOGvdsKw.js",
                  "cached": true
                }
              ]
            }
          ]
        },
        "react/jsx-runtime": {
          "dirty": false,
          "versions": [
            {
              "tag": "18.3.1",
              "action": "share",
              "host": false,
              "remotes": [
                {
                  "name": "whiteboard",
                  "requiredVersion": "^18.3.1",
                  "strictVersion": true,
                  "file": "react_jsx_runtime.RDhwXXoxCg.js",
                  "cached": true
                }
              ]
            }
          ]
        },
        "rxjs": {
          "dirty": false,
          "versions": [
            {
              "tag": "7.8.2",
              "action": "share",
              "host": true,
              "remotes": [
                {
                  "name": "__NF-HOST__",
                  "requiredVersion": "~7.8.0",
                  "strictVersion": true,
                  "file": "rxjs.IJzVNeB5rY.js",
                  "cached": true
                }
              ]
            }
          ]
        },
        "rxjs/operators": {
          "dirty": false,
          "versions": [
            {
              "tag": "7.8.2",
              "action": "share",
              "host": true,
              "remotes": [
                {
                  "name": "__NF-HOST__",
                  "requiredVersion": "~7.8.0",
                  "strictVersion": true,
                  "file": "rxjs_operators.gdYSvUruih.js",
                  "cached": true
                }
              ]
            }
          ]
        },
        "tslib": {
          "dirty": false,
          "versions": [
            {
              "tag": "2.8.1",
              "action": "share",
              "host": true,
              "remotes": [
                {
                  "name": "__NF-HOST__",
                  "requiredVersion": "^2.3.0",
                  "strictVersion": true,
                  "file": "tslib.s6WVYyl__v.js",
                  "cached": true
                }
              ]
            }
          ]
        }
      }
    },
    "sharedChunks": {
      "__NF-HOST__": {
        "browser-angular_common": [
          "chunk-WW26EZ22.js"
        ],
        "browser-angular_core": [
          "chunk-RCIWTGS7.js",
          "chunk-K6ZMRNMW.js",
          "chunk-APTZXQMF.js",
          "chunk-V2SUVJ7R.js",
          "chunk-2VMXMS7J.js"
        ],
        "browser-rxjs": [
          "chunk-PAMKM67I.js"
        ],
        "mapping-or-exposed": []
      }
    }
  },
  "importMaps": {
    "documentMaps": [
      {
        "kind": "importmap-shim",
        "parsed": true,
        "importCount": 22,
        "scopeCount": 1
      }
    ],
    "effective": {
      "imports": [
        {
          "specifier": "@excalidraw/excalidraw",
          "target": "http://127.0.0.1:8088/frankenstein-meeting-room/whiteboard/_excalidraw_excalidraw.0MlOv2WvQj.js"
        },
        {
          "specifier": "react",
          "target": "http://127.0.0.1:8088/frankenstein-meeting-room/whiteboard/react.QYXZqQxJ1j.js"
        },
        {
          "specifier": "react/jsx-runtime",
          "target": "http://127.0.0.1:8088/frankenstein-meeting-room/whiteboard/react_jsx_runtime.RDhwXXoxCg.js"
        },
        {
          "specifier": "react/jsx-dev-runtime",
          "target": "http://127.0.0.1:8088/frankenstein-meeting-room/whiteboard/react_jsx_dev_runtime.UsMOGvdsKw.js"
        },
        {
          "specifier": "react-dom",
          "target": "http://127.0.0.1:8088/frankenstein-meeting-room/whiteboard/react_dom.6SKyvL_ZIW.js"
        },
        {
          "specifier": "react-dom/client",
          "target": "http://127.0.0.1:8088/frankenstein-meeting-room/whiteboard/react_dom_client.lVKcx-4-HL.js"
        },
        {
          "specifier": "react-dom/profiling",
          "target": "http://127.0.0.1:8088/frankenstein-meeting-room/whiteboard/react_dom_profiling.wPFH8wjIJf.js"
        },
        {
          "specifier": "mermaid",
          "target": "http://127.0.0.1:8088/frankenstein-meeting-room/mermaid/mermaid.fMI3T940QA.js"
        },
        {
          "specifier": "@angular/common",
          "target": "http://127.0.0.1:8088/frankenstein-meeting-room/_angular_common.Ucn2BmyRM1.js"
        },
        {
          "specifier": "@angular/common/http",
          "target": "http://127.0.0.1:8088/frankenstein-meeting-room/_angular_common_http.XnycUwbhpt.js"
        },
        {
          "specifier": "@angular/platform-browser",
          "target": "http://127.0.0.1:8088/frankenstein-meeting-room/_angular_platform_browser.lAyP2N3Pw8.js"
        },
        {
          "specifier": "rxjs",
          "target": "http://127.0.0.1:8088/frankenstein-meeting-room/rxjs.IJzVNeB5rY.js"
        },
        {
          "specifier": "rxjs/operators",
          "target": "http://127.0.0.1:8088/frankenstein-meeting-room/rxjs_operators.gdYSvUruih.js"
        },
        {
          "specifier": "tslib",
          "target": "http://127.0.0.1:8088/frankenstein-meeting-room/tslib.s6WVYyl__v.js"
        },
        {
          "specifier": "@angular/core",
          "target": "http://127.0.0.1:8088/frankenstein-meeting-room/_angular_core.RHjtWEkOzP.js"
        },
        {
          "specifier": "@angular/core/event-dispatch-contract.min.js",
          "target": "http://127.0.0.1:8088/frankenstein-meeting-room/_angular_core_event_dispatch_contract_min_js.JotK85OfcE.js"
        },
        {
          "specifier": "@angular/core/primitives/di",
          "target": "http://127.0.0.1:8088/frankenstein-meeting-room/_angular_core_primitives_di.QUc60-Xs6C.js"
        },
        {
          "specifier": "@angular/core/primitives/event-dispatch",
          "target": "http://127.0.0.1:8088/frankenstein-meeting-room/_angular_core_primitives_event_dispatch.1A9qBws3LP.js"
        },
        {
          "specifier": "@angular/core/primitives/signals",
          "target": "http://127.0.0.1:8088/frankenstein-meeting-room/_angular_core_primitives_signals.ePwPWbaXlE.js"
        },
        {
          "specifier": "@angular/core/rxjs-interop",
          "target": "http://127.0.0.1:8088/frankenstein-meeting-room/_angular_core_rxjs_interop.YqevhcoUQy.js"
        },
        {
          "specifier": "whiteboard/./Bootstrap",
          "target": "http://127.0.0.1:8088/frankenstein-meeting-room/whiteboard/Bootstrap-7COJRA5I.js"
        },
        {
          "specifier": "mermaid/./Bootstrap",
          "target": "http://127.0.0.1:8088/frankenstein-meeting-room/mermaid/Bootstrap-BBNZEAEH.js"
        }
      ],
      "scopes": [
        {
          "scope": "http://127.0.0.1:8088/frankenstein-meeting-room/",
          "imports": [
            {
              "specifier": "@nf-internal/chunk-WW26EZ22",
              "target": "http://127.0.0.1:8088/frankenstein-meeting-room/chunk-WW26EZ22.js"
            },
            {
              "specifier": "@nf-internal/chunk-PAMKM67I",
              "target": "http://127.0.0.1:8088/frankenstein-meeting-room/chunk-PAMKM67I.js"
            },
            {
              "specifier": "@nf-internal/chunk-RCIWTGS7",
              "target": "http://127.0.0.1:8088/frankenstein-meeting-room/chunk-RCIWTGS7.js"
            },
            {
              "specifier": "@nf-internal/chunk-K6ZMRNMW",
              "target": "http://127.0.0.1:8088/frankenstein-meeting-room/chunk-K6ZMRNMW.js"
            },
            {
              "specifier": "@nf-internal/chunk-APTZXQMF",
              "target": "http://127.0.0.1:8088/frankenstein-meeting-room/chunk-APTZXQMF.js"
            },
            {
              "specifier": "@nf-internal/chunk-V2SUVJ7R",
              "target": "http://127.0.0.1:8088/frankenstein-meeting-room/chunk-V2SUVJ7R.js"
            },
            {
              "specifier": "@nf-internal/chunk-2VMXMS7J",
              "target": "http://127.0.0.1:8088/frankenstein-meeting-room/chunk-2VMXMS7J.js"
            }
          ]
        }
      ],
      "integrityFor": [
        "http://127.0.0.1:8088/frankenstein-meeting-room/whiteboard/_excalidraw_excalidraw.0MlOv2WvQj.js",
        "http://127.0.0.1:8088/frankenstein-meeting-room/whiteboard/react.QYXZqQxJ1j.js",
        "http://127.0.0.1:8088/frankenstein-meeting-room/whiteboard/react_jsx_runtime.RDhwXXoxCg.js",
        "http://127.0.0.1:8088/frankenstein-meeting-room/whiteboard/react_jsx_dev_runtime.UsMOGvdsKw.js",
        "http://127.0.0.1:8088/frankenstein-meeting-room/whiteboard/react_dom.6SKyvL_ZIW.js",
        "http://127.0.0.1:8088/frankenstein-meeting-room/whiteboard/react_dom_client.lVKcx-4-HL.js",
        "http://127.0.0.1:8088/frankenstein-meeting-room/whiteboard/react_dom_profiling.wPFH8wjIJf.js",
        "http://127.0.0.1:8088/frankenstein-meeting-room/mermaid/mermaid.fMI3T940QA.js",
        "http://127.0.0.1:8088/frankenstein-meeting-room/_angular_common.Ucn2BmyRM1.js",
        "http://127.0.0.1:8088/frankenstein-meeting-room/_angular_common_http.XnycUwbhpt.js",
        "http://127.0.0.1:8088/frankenstein-meeting-room/_angular_platform_browser.lAyP2N3Pw8.js",
        "http://127.0.0.1:8088/frankenstein-meeting-room/rxjs.IJzVNeB5rY.js",
        "http://127.0.0.1:8088/frankenstein-meeting-room/rxjs_operators.gdYSvUruih.js",
        "http://127.0.0.1:8088/frankenstein-meeting-room/tslib.s6WVYyl__v.js",
        "http://127.0.0.1:8088/frankenstein-meeting-room/_angular_core.RHjtWEkOzP.js",
        "http://127.0.0.1:8088/frankenstein-meeting-room/_angular_core_event_dispatch_contract_min_js.JotK85OfcE.js",
        "http://127.0.0.1:8088/frankenstein-meeting-room/_angular_core_primitives_di.QUc60-Xs6C.js",
        "http://127.0.0.1:8088/frankenstein-meeting-room/_angular_core_primitives_event_dispatch.1A9qBws3LP.js",
        "http://127.0.0.1:8088/frankenstein-meeting-room/_angular_core_primitives_signals.ePwPWbaXlE.js",
        "http://127.0.0.1:8088/frankenstein-meeting-room/_angular_core_rxjs_interop.YqevhcoUQy.js",
        "http://127.0.0.1:8088/frankenstein-meeting-room/whiteboard/Bootstrap-7COJRA5I.js",
        "http://127.0.0.1:8088/frankenstein-meeting-room/mermaid/Bootstrap-BBNZEAEH.js",
        "http://127.0.0.1:8088/frankenstein-meeting-room/chunk-WW26EZ22.js",
        "http://127.0.0.1:8088/frankenstein-meeting-room/chunk-PAMKM67I.js",
        "http://127.0.0.1:8088/frankenstein-meeting-room/chunk-RCIWTGS7.js",
        "http://127.0.0.1:8088/frankenstein-meeting-room/chunk-K6ZMRNMW.js",
        "http://127.0.0.1:8088/frankenstein-meeting-room/chunk-APTZXQMF.js",
        "http://127.0.0.1:8088/frankenstein-meeting-room/chunk-V2SUVJ7R.js",
        "http://127.0.0.1:8088/frankenstein-meeting-room/chunk-2VMXMS7J.js"
      ]
    }
  },
  "errors": []
} satisfies SnapshotV1;
