// GENERATED by scripts/derive-fixtures.mjs — do not edit by hand; re-run the script.
// Source: captures/non-dense/20260811T095326Z.json (corpus run 20260811T095850Z),
// envelope lab-lossless-capture/1, orchestrator dev commit 8e5e0b3, observed
// generation: dev — see captures/README.md for provenance.
// Derived through the real collector pipeline (capture-seeded page → probe
// eval → mapProbeResult), so the fixture equals pipeline output by construction.

import { SnapshotV1 } from '../snapshot-v1';

export const nonDenseFixture = {
  "schemaVersion": 1,
  "capture": {
    "pageUrl": "http://localhost:4300/",
    "capturedAt": "2026-08-11T09:53:58.741Z",
    "mode": "passive",
    "collectorVersion": "nf-devtools-collector/2"
  },
  "channels": {
    "nativeFederationGlobals": {
      "state": "available"
    },
    "domImportMaps": {
      "state": "available"
    },
    "importShim": {
      "state": "available"
    }
  },
  "runtime": {
    "remotes": {
      "mfe3": {
        "scopeUrl": "./mfe3/",
        "exposes": [
          {
            "moduleName": "./Component",
            "file": "Component-KYAYWGQO.js"
          }
        ],
        "integrity": {}
      },
      "__NF-HOST__": {
        "scopeUrl": "./",
        "exposes": [],
        "integrity": {}
      }
    },
    "scopedExternals": {
      "mfe3": {
        "@nf-internal/chunk-G4MQRHIT": {
          "tag": "0.0.0",
          "bundle": null,
          "entries": {
            "@nf-internal/chunk-G4MQRHIT": "chunk-G4MQRHIT.js"
          }
        },
        "@nf-internal/chunk-CTZ4MUAG": {
          "tag": "0.0.0",
          "bundle": null,
          "entries": {
            "@nf-internal/chunk-CTZ4MUAG": "chunk-CTZ4MUAG.js"
          }
        },
        "@nf-internal/chunk-3O3QUTWM": {
          "tag": "0.0.0",
          "bundle": null,
          "entries": {
            "@nf-internal/chunk-3O3QUTWM": "chunk-3O3QUTWM.js"
          }
        },
        "@nf-internal/chunk-DXWTOITO": {
          "tag": "0.0.0",
          "bundle": null,
          "entries": {
            "@nf-internal/chunk-DXWTOITO": "chunk-DXWTOITO.js"
          }
        },
        "@nf-internal/chunk-DLJHBHZE": {
          "tag": "0.0.0",
          "bundle": null,
          "entries": {
            "@nf-internal/chunk-DLJHBHZE": "chunk-DLJHBHZE.js"
          }
        },
        "@nf-internal/chunk-PZNONLPT": {
          "tag": "0.0.0",
          "bundle": null,
          "entries": {
            "@nf-internal/chunk-PZNONLPT": "chunk-PZNONLPT.js"
          }
        },
        "@nf-internal/chunk-KNUKVBCT": {
          "tag": "0.0.0",
          "bundle": null,
          "entries": {
            "@nf-internal/chunk-KNUKVBCT": "chunk-KNUKVBCT.js"
          }
        }
      }
    },
    "sharedExternals": {
      "__GLOBAL__": {
        "@nf-lab/conflict-lib": {
          "dirty": false,
          "versions": [
            {
              "tag": "1.0.0",
              "action": "share",
              "host": false,
              "remotes": [
                {
                  "name": "mfe3",
                  "requiredVersion": "file:../../packages/conflict-lib/v1",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/conflict-lib": "_nf_lab_conflict_lib.JF7uEdSVsN.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/conflict-lib",
                      "file": "_nf_lab_conflict_lib.JF7uEdSVsN.js"
                    }
                  ],
                  "generation": "dev"
                }
              ]
            }
          ]
        },
        "@angular/common": {
          "dirty": false,
          "versions": [
            {
              "tag": "22.0.8",
              "action": "share",
              "host": false,
              "remotes": [
                {
                  "name": "mfe3",
                  "requiredVersion": "~22.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@angular/common": "_angular_common.2lRkWlIXsD.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "servedFiles": [
                    {
                      "entry": "@angular/common",
                      "file": "_angular_common.2lRkWlIXsD.js"
                    }
                  ],
                  "generation": "dev"
                }
              ]
            }
          ]
        },
        "@angular/common/http": {
          "dirty": false,
          "versions": [
            {
              "tag": "22.0.8",
              "action": "share",
              "host": false,
              "remotes": [
                {
                  "name": "mfe3",
                  "requiredVersion": "~22.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@angular/common/http": "_angular_common_http.93X-PjezxZ.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "servedFiles": [
                    {
                      "entry": "@angular/common/http",
                      "file": "_angular_common_http.93X-PjezxZ.js"
                    }
                  ],
                  "generation": "dev"
                }
              ]
            }
          ]
        },
        "@angular/core": {
          "dirty": false,
          "versions": [
            {
              "tag": "22.0.8",
              "action": "share",
              "host": false,
              "remotes": [
                {
                  "name": "mfe3",
                  "requiredVersion": "~22.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@angular/core": "_angular_core.X3ivyfrWNn.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "servedFiles": [
                    {
                      "entry": "@angular/core",
                      "file": "_angular_core.X3ivyfrWNn.js"
                    }
                  ],
                  "generation": "dev"
                }
              ]
            }
          ]
        },
        "@angular/core/event-dispatch-contract.min.js": {
          "dirty": false,
          "versions": [
            {
              "tag": "22.0.8",
              "action": "share",
              "host": false,
              "remotes": [
                {
                  "name": "mfe3",
                  "requiredVersion": "~22.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@angular/core/event-dispatch-contract.min.js": "_angular_core_event_dispatch_contract_min_js.3axcNP9xmW.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "servedFiles": [
                    {
                      "entry": "@angular/core/event-dispatch-contract.min.js",
                      "file": "_angular_core_event_dispatch_contract_min_js.3axcNP9xmW.js"
                    }
                  ],
                  "generation": "dev"
                }
              ]
            }
          ]
        },
        "@angular/core/primitives/di": {
          "dirty": false,
          "versions": [
            {
              "tag": "22.0.8",
              "action": "share",
              "host": false,
              "remotes": [
                {
                  "name": "mfe3",
                  "requiredVersion": "~22.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@angular/core/primitives/di": "_angular_core_primitives_di.EObUKH7oSG.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "servedFiles": [
                    {
                      "entry": "@angular/core/primitives/di",
                      "file": "_angular_core_primitives_di.EObUKH7oSG.js"
                    }
                  ],
                  "generation": "dev"
                }
              ]
            }
          ]
        },
        "@angular/core/primitives/event-dispatch": {
          "dirty": false,
          "versions": [
            {
              "tag": "22.0.8",
              "action": "share",
              "host": false,
              "remotes": [
                {
                  "name": "mfe3",
                  "requiredVersion": "~22.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@angular/core/primitives/event-dispatch": "_angular_core_primitives_event_dispatch.hU2Qzjyqeh.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "servedFiles": [
                    {
                      "entry": "@angular/core/primitives/event-dispatch",
                      "file": "_angular_core_primitives_event_dispatch.hU2Qzjyqeh.js"
                    }
                  ],
                  "generation": "dev"
                }
              ]
            }
          ]
        },
        "@angular/core/primitives/signals": {
          "dirty": false,
          "versions": [
            {
              "tag": "22.0.8",
              "action": "share",
              "host": false,
              "remotes": [
                {
                  "name": "mfe3",
                  "requiredVersion": "~22.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@angular/core/primitives/signals": "_angular_core_primitives_signals.CVk74cDF7r.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "servedFiles": [
                    {
                      "entry": "@angular/core/primitives/signals",
                      "file": "_angular_core_primitives_signals.CVk74cDF7r.js"
                    }
                  ],
                  "generation": "dev"
                }
              ]
            }
          ]
        },
        "@angular/core/rxjs-interop": {
          "dirty": false,
          "versions": [
            {
              "tag": "22.0.8",
              "action": "share",
              "host": false,
              "remotes": [
                {
                  "name": "mfe3",
                  "requiredVersion": "~22.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@angular/core/rxjs-interop": "_angular_core_rxjs_interop.__1TDonEXD.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "servedFiles": [
                    {
                      "entry": "@angular/core/rxjs-interop",
                      "file": "_angular_core_rxjs_interop.__1TDonEXD.js"
                    }
                  ],
                  "generation": "dev"
                }
              ]
            }
          ]
        },
        "@angular/elements": {
          "dirty": false,
          "versions": [
            {
              "tag": "22.0.8",
              "action": "share",
              "host": false,
              "remotes": [
                {
                  "name": "mfe3",
                  "requiredVersion": "~22.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@angular/elements": "_angular_elements.ktmx-SsBF0.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "servedFiles": [
                    {
                      "entry": "@angular/elements",
                      "file": "_angular_elements.ktmx-SsBF0.js"
                    }
                  ],
                  "generation": "dev"
                }
              ]
            }
          ]
        },
        "@angular/platform-browser": {
          "dirty": false,
          "versions": [
            {
              "tag": "22.0.8",
              "action": "share",
              "host": false,
              "remotes": [
                {
                  "name": "mfe3",
                  "requiredVersion": "~22.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@angular/platform-browser": "_angular_platform_browser.djzJcPG8PR.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "servedFiles": [
                    {
                      "entry": "@angular/platform-browser",
                      "file": "_angular_platform_browser.djzJcPG8PR.js"
                    }
                  ],
                  "generation": "dev"
                }
              ]
            }
          ]
        },
        "rxjs": {
          "dirty": false,
          "versions": [
            {
              "tag": "7.8.2",
              "action": "share",
              "host": false,
              "remotes": [
                {
                  "name": "mfe3",
                  "requiredVersion": "~7.8.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "rxjs": "rxjs.AD771FvZRA.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "servedFiles": [
                    {
                      "entry": "rxjs",
                      "file": "rxjs.AD771FvZRA.js"
                    }
                  ],
                  "generation": "dev"
                }
              ]
            }
          ]
        },
        "rxjs/operators": {
          "dirty": false,
          "versions": [
            {
              "tag": "7.8.2",
              "action": "share",
              "host": false,
              "remotes": [
                {
                  "name": "mfe3",
                  "requiredVersion": "~7.8.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "rxjs/operators": "rxjs_operators.t7RGhKl4M9.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "servedFiles": [
                    {
                      "entry": "rxjs/operators",
                      "file": "rxjs_operators.t7RGhKl4M9.js"
                    }
                  ],
                  "generation": "dev"
                }
              ]
            }
          ]
        },
        "tslib": {
          "dirty": false,
          "versions": [
            {
              "tag": "2.8.1",
              "action": "share",
              "host": false,
              "remotes": [
                {
                  "name": "mfe3",
                  "requiredVersion": "^2.3.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "tslib": "tslib.BX2MinpEcV.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "servedFiles": [
                    {
                      "entry": "tslib",
                      "file": "tslib.BX2MinpEcV.js"
                    }
                  ],
                  "generation": "dev"
                }
              ]
            }
          ]
        }
      }
    },
    "sharedChunks": {
      "__NF-HOST__": {
        "mapping-or-exposed": []
      }
    },
    "generation": "dev"
  },
  "importMaps": {
    "documentMaps": [
      {
        "kind": "importmap",
        "parsed": true,
        "importCount": 15,
        "scopeCount": 1
      }
    ],
    "effective": {
      "imports": [],
      "scopes": [],
      "integrityFor": []
    }
  },
  "errors": []
} satisfies SnapshotV1;
