// GENERATED by scripts/derive-fixtures.mjs — do not edit by hand; re-run the script.
// Source: captures/scope-isolation/20260811T094911Z.json (corpus run 20260811T095850Z),
// envelope lab-lossless-capture/1, orchestrator dev commit 8e5e0b3, observed
// generation: dev — see captures/README.md for provenance.
// Derived through the real collector pipeline (capture-seeded page → probe
// eval → mapProbeResult), so the fixture equals pipeline output by construction.

import { SnapshotV1 } from '../snapshot-v1';

export const scopeIsolationFixture = {
  "schemaVersion": 1,
  "capture": {
    "pageUrl": "http://localhost:4300/",
    "capturedAt": "2026-08-11T09:49:43.007Z",
    "mode": "passive",
    "collectorVersion": "nf-devtools-collector/2"
  },
  "channels": {
    "nativeFederationGlobals": {
      "state": "available"
    },
    "domImportMaps": {
      "state": "available"
    },
    "importShim": {
      "state": "available"
    }
  },
  "runtime": {
    "remotes": {
      "mfe1": {
        "scopeUrl": "./mfe1/",
        "exposes": [
          {
            "moduleName": "./Component",
            "file": "Component-RJXV7SVT.js"
          }
        ],
        "integrity": {}
      },
      "__NF-HOST__": {
        "scopeUrl": "./",
        "exposes": [],
        "integrity": {}
      }
    },
    "scopedExternals": {},
    "sharedExternals": {
      "__GLOBAL__": {
        "@nf-lab/conflict-lib": {
          "dirty": false,
          "versions": [
            {
              "tag": "2.0.0",
              "action": "share",
              "host": true,
              "remotes": [
                {
                  "name": "__NF-HOST__",
                  "requiredVersion": ">=1.0.0 <3.0.0",
                  "strictVersion": false,
                  "file": null,
                  "entries": {
                    "@nf-lab/conflict-lib": "_nf_lab_conflict_lib.jvcc6K1csg.js"
                  },
                  "cached": true,
                  "bundle": "browser-shared",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/conflict-lib",
                      "file": "_nf_lab_conflict_lib.jvcc6K1csg.js"
                    }
                  ],
                  "generation": "dev"
                }
              ]
            },
            {
              "tag": "1.0.0",
              "action": "scope",
              "host": false,
              "remotes": [
                {
                  "name": "mfe1",
                  "requiredVersion": "~1.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/conflict-lib": "_nf_lab_conflict_lib.JF7uEdSVsN.js"
                  },
                  "cached": true,
                  "bundle": "browser-shared",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/conflict-lib",
                      "file": "_nf_lab_conflict_lib.JF7uEdSVsN.js"
                    }
                  ],
                  "generation": "dev"
                }
              ]
            }
          ]
        }
      }
    },
    "sharedChunks": {
      "mfe1": {
        "mapping-or-exposed": []
      },
      "__NF-HOST__": {
        "mapping-or-exposed": []
      }
    },
    "generation": "dev"
  },
  "importMaps": {
    "documentMaps": [
      {
        "kind": "importmap",
        "parsed": true,
        "importCount": 2,
        "scopeCount": 1
      }
    ],
    "effective": {
      "imports": [],
      "scopes": [],
      "integrityFor": []
    }
  },
  "errors": []
} satisfies SnapshotV1;
